import { PostList } from '@/components/post-list';
import { ProductList } from '@/components/product-list';

export default function Blog() {
  return (
    <>
      <section className="flex min-h-52 flex-col items-center justify-center gap-4 text-center">
        <h2 className="font-black text-3xl lg:text-5xl">Blog</h2>
        <p className="text-sm md:text-base">All Posts generated by AI</p>
      </section>
      <PostList />
    </>
  );
}
